
spring:
  security:
    user.name: admin # Default user name.
    user.password: foobar # Password
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
  h2:
    console.enabled: true


server:
  port: 8081
